packages:
  - '.'

allowBuilds:
  msgpackr-extract: true
  msw: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - oxlint-plugin-react-doctor@0.2.14
  - react-doctor@0.2.14

publicHoistPattern:
  - '@inertiajs/core'
