import type { PageBuilderConfig } from "./blocks/types";
import {
  AboutCustomComponentConfig,
  AboutSectionComponentConfig,
  AnnouncementsCustomComponentConfig,
  AuthStatusComponentConfig,
  BadgeListComponentConfig,
  ButtonComponentConfig,
  ButtonGroupComponentConfig,
  CTASectionComponentConfig,
  CardComponentConfig,
  CarouselSectionComponentConfig,
  CategoriesComponentConfig,
  ContactInfoComponentConfig,
  ContainerComponentConfig,
  CopyrightBarComponentConfig,
  CtaCustomComponentConfig,
  DividerComponentConfig,
  FAQSectionComponentConfig,
  FeatureGridComponentConfig,
  FitFooterComponentConfig,
  FitNavigationHeaderComponentConfig,
  FlexComponentConfig,
  GridComponentConfig,
  HeadingComponentConfig,
  HeroBannerComponentConfig,
  HeroCustomComponentConfig,
  HeroSplitComponentConfig,
  ImageComponentConfig,
  ImageTextComponentConfig,
  LatestAnnouncementsComponentConfig,
  LatestPostsComponentConfig,
  LinkListComponentConfig,
  MilestonesComponentConfig,
  NavigationMenuComponentConfig,
  NewsletterFormComponentConfig,
  NewsCustomComponentConfig,
  NoteComponentConfig,
  PageLinksComponentConfig,
  PostHeaderComponentConfig,
  ProgramsCustomComponentConfig,
  RelatedPostsComponentConfig,
  RichTextComponentConfig,
  SectionComponentConfig,
  SidebarQuickLinksComponentConfig,
  SidebarSupportComponentConfig,
  SiteLayoutFrameComponentConfig,
  SocialLinksComponentConfig,
  SpacerComponentConfig,
  StaffGridComponentConfig,
  StaffProfileCardComponentConfig,
  StatsCustomComponentConfig,
  StatsSectionComponentConfig,
  TagListComponentConfig,
  TestimonialSectionComponentConfig,
  TimelineSectionComponentConfig,
  TwoColumnsComponentConfig,
  UnitListComponentConfig,
} from "./blocks";
import { withSelectFieldDefaults } from "./blocks/shared";
import { getPuckEnglishName } from "./component-types";

const baseComponents: Record<string, any> = {
  SiteLayoutFrame: SiteLayoutFrameComponentConfig,
  Section: SectionComponentConfig,
  Container: ContainerComponentConfig,
  TwoColumns: TwoColumnsComponentConfig,
  Spacer: SpacerComponentConfig,
  Divider: DividerComponentConfig,
  Grid: GridComponentConfig,
  Flex: FlexComponentConfig,
  Heading: HeadingComponentConfig,
  RichText: RichTextComponentConfig,
  Image: ImageComponentConfig,
  ImageText: ImageTextComponentConfig,
  Button: ButtonComponentConfig,
  ButtonGroup: ButtonGroupComponentConfig,
  Card: CardComponentConfig,
  Note: NoteComponentConfig,
  BadgeList: BadgeListComponentConfig,
  TagList: TagListComponentConfig,
  AboutSection: AboutSectionComponentConfig,
  FeatureGrid: FeatureGridComponentConfig,
  StatsSection: StatsSectionComponentConfig,
  CTASection: CTASectionComponentConfig,
  TimelineSection: TimelineSectionComponentConfig,
  FAQSection: FAQSectionComponentConfig,
  TestimonialSection: TestimonialSectionComponentConfig,
  CarouselSection: CarouselSectionComponentConfig,
  HeroBanner: HeroBannerComponentConfig,
  HeroSplit: HeroSplitComponentConfig,
  FeaturedHero: HeroCustomComponentConfig,
  HighlightStats: StatsCustomComponentConfig,
  ProgramGrid: ProgramsCustomComponentConfig,
  AboutFeature: AboutCustomComponentConfig,
  Milestones: MilestonesComponentConfig,
  FeaturedNews: NewsCustomComponentConfig,
  FeaturedAnnouncements: AnnouncementsCustomComponentConfig,
  EnrollmentCta: CtaCustomComponentConfig,
  PostDetailHeader: PostHeaderComponentConfig,
  SidebarQuickLinks: SidebarQuickLinksComponentConfig,
  SidebarSupport: SidebarSupportComponentConfig,
  PostFeed: LatestPostsComponentConfig,
  AnnouncementFeed: LatestAnnouncementsComponentConfig,
  StaffGrid: StaffGridComponentConfig,
  StaffProfileCard: StaffProfileCardComponentConfig,
  UnitList: UnitListComponentConfig,
  RelatedPostFeed: RelatedPostsComponentConfig,
  SiteHeader: FitNavigationHeaderComponentConfig,
  SiteFooter: FitFooterComponentConfig,
  NavigationMenu: NavigationMenuComponentConfig,
  PostCategoryList: CategoriesComponentConfig,
  PageLinkList: PageLinksComponentConfig,
  CustomLinkList: LinkListComponentConfig,
  ContactInfo: ContactInfoComponentConfig,
  SocialLinks: SocialLinksComponentConfig,
  NewsletterForm: NewsletterFormComponentConfig,
  CopyrightBar: CopyrightBarComponentConfig,
  AuthLinks: AuthStatusComponentConfig,
};

export const pageBuilderComponents = withSelectFieldDefaults(
  Object.fromEntries(
    Object.entries(baseComponents).map(([componentName, componentConfig]) => [
      componentName,
      {
        ...componentConfig,
        metadata: {
          ...componentConfig.metadata,
          englishName: getPuckEnglishName(componentName),
        },
      },
    ]),
  ) as PageBuilderConfig["components"],
);
