import {
  GridComponentConfig,
  FlexComponentConfig,
  HeroBannerComponentConfig,
  HeroSplitComponentConfig,
  SectionComponentConfig,
  ContainerComponentConfig,
  TwoColumnsComponentConfig,
  SpacerComponentConfig,
  DividerComponentConfig,
  HeadingComponentConfig,
  RichTextComponentConfig,
  ImageComponentConfig,
  ImageTextComponentConfig,
  ButtonComponentConfig,
  ButtonGroupComponentConfig,
  CardComponentConfig,
  NoteComponentConfig,
  BadgeListComponentConfig,
  TagListComponentConfig,
  AboutSectionComponentConfig,
  FeatureGridComponentConfig,
  StatsSectionComponentConfig,
  CTASectionComponentConfig,
  TimelineSectionComponentConfig,
  FAQSectionComponentConfig,
  TestimonialSectionComponentConfig,
  CarouselSectionComponentConfig,
  LatestPostsComponentConfig,
  LatestAnnouncementsComponentConfig,
  StaffGridComponentConfig,
  UnitListComponentConfig,
  DocumentListComponentConfig,
  RelatedPostsComponentConfig,
  RelatedDocumentsComponentConfig,
  AuthStatusComponentConfig,
  NavigationMenuComponentConfig,
  CategoriesComponentConfig,
  PageLinksComponentConfig,
  LinkListComponentConfig,
  ContactInfoComponentConfig,
  SiteLayoutFrameComponentConfig,
  SocialLinksComponentConfig,
  NewsletterFormComponentConfig,
  CopyrightBarComponentConfig,
} from "../blocks";
import type { PageBuilderConfig } from "../blocks/types";

export const pageConfig: PageBuilderConfig = {
  categories: {
    layout_blocks: {
      title: "1. Bố cục",
      components: [
        "Section",
        "Container",
        "TwoColumns",
        "Spacer",
        "Divider",
        "Grid",
        "Flex",
      ],
    },
    content_blocks: {
      title: "2. Nội dung",
      components: [
        "Heading",
        "RichText",
        "Image",
        "ImageText",
        "Button",
        "ButtonGroup",
        "Card",
        "Note",
        "BadgeList",
        "TagList",
        "SocialLinks",
        "NewsletterForm",
        "CopyrightBar",
      ],
    },
    section_blocks: {
      title: "3. Khối giao diện",
      components: [
        "AboutSection",
        "FeatureGrid",
        "StatsSection",
        "CTASection",
        "TimelineSection",
        "FAQSection",
        "TestimonialSection",
        "CarouselSection",
        "HeroBanner",
        "HeroSplit",
      ],
    },
    dynamic_blocks: {
      title: "4. Khối dữ liệu",
      components: [
        "LatestPosts",
        "LatestAnnouncements",
        "StaffGrid",
        "UnitList",
        "DocumentList",
        "RelatedPosts",
        "RelatedDocuments",
        "NavigationMenu",
        "Categories",
        "PageLinks",
        "LinkList",
        "ContactInfo",
      ],
    },
  },
  root: {
    render: ({ children }) => (
      <article className="font-sans space-y-12 rounded-3xl bg-bg p-4 sm:p-8">
        {children}
      </article>
    ),
  },
  components: {
    SiteLayoutFrame: SiteLayoutFrameComponentConfig,

    Section: SectionComponentConfig,
    Container: ContainerComponentConfig,
    TwoColumns: TwoColumnsComponentConfig,
    Spacer: SpacerComponentConfig,
    Divider: DividerComponentConfig,
    Grid: GridComponentConfig,
    Flex: FlexComponentConfig,

    Heading: HeadingComponentConfig,
    RichText: RichTextComponentConfig,
    Image: ImageComponentConfig,
    ImageText: ImageTextComponentConfig,
    Button: ButtonComponentConfig,
    ButtonGroup: ButtonGroupComponentConfig,
    Card: CardComponentConfig,
    Note: NoteComponentConfig,
    BadgeList: BadgeListComponentConfig,
    TagList: TagListComponentConfig,

    AboutSection: AboutSectionComponentConfig,
    FeatureGrid: FeatureGridComponentConfig,
    StatsSection: StatsSectionComponentConfig,
    CTASection: CTASectionComponentConfig,
    TimelineSection: TimelineSectionComponentConfig,
    FAQSection: FAQSectionComponentConfig,
    TestimonialSection: TestimonialSectionComponentConfig,
    CarouselSection: CarouselSectionComponentConfig,
    HeroBanner: HeroBannerComponentConfig,
    HeroSplit: HeroSplitComponentConfig,

    LatestPosts: LatestPostsComponentConfig,
    LatestAnnouncements: LatestAnnouncementsComponentConfig,
    StaffGrid: StaffGridComponentConfig,
    UnitList: UnitListComponentConfig,
    DocumentList: DocumentListComponentConfig,
    RelatedPosts: RelatedPostsComponentConfig,
    RelatedDocuments: RelatedDocumentsComponentConfig,
    NavigationMenu: NavigationMenuComponentConfig,
    Categories: CategoriesComponentConfig,
    PageLinks: PageLinksComponentConfig,
    LinkList: LinkListComponentConfig,
    ContactInfo: ContactInfoComponentConfig,
    SocialLinks: SocialLinksComponentConfig,
    NewsletterForm: NewsletterFormComponentConfig,
    CopyrightBar: CopyrightBarComponentConfig,
    AuthStatus: AuthStatusComponentConfig,
  },
};
