import {
  GridComponentConfig,
  FlexComponentConfig,
  HeroBannerComponentConfig,
  HeroSplitComponentConfig,
  HeroCustomComponentConfig,
  StatsCustomComponentConfig,
  SectionComponentConfig,
  ContainerComponentConfig,
  TwoColumnsComponentConfig,
  SpacerComponentConfig,
  DividerComponentConfig,
  HeadingComponentConfig,
  RichTextComponentConfig,
  ImageComponentConfig,
  ImageTextComponentConfig,
  ButtonComponentConfig,
  ButtonGroupComponentConfig,
  CardComponentConfig,
  NoteComponentConfig,
  BadgeListComponentConfig,
  TagListComponentConfig,
  AboutSectionComponentConfig,
  FeatureGridComponentConfig,
  StatsSectionComponentConfig,
  CTASectionComponentConfig,
  TimelineSectionComponentConfig,
  FAQSectionComponentConfig,
  TestimonialSectionComponentConfig,
  CarouselSectionComponentConfig,
  LatestPostsComponentConfig,
  LatestAnnouncementsComponentConfig,
  StaffGridComponentConfig,
  StaffProfileCardComponentConfig,
  UnitListComponentConfig,
  RelatedPostsComponentConfig,
  FitNavigationHeaderComponentConfig,
  FitFooterComponentConfig,
  AuthStatusComponentConfig,
  NavigationMenuComponentConfig,
  CategoriesComponentConfig,
  PageLinksComponentConfig,
  LinkListComponentConfig,
  ContactInfoComponentConfig,
  SiteLayoutFrameComponentConfig,
  SocialLinksComponentConfig,
  NewsletterFormComponentConfig,
  CopyrightBarComponentConfig,
  ProgramsCustomComponentConfig,
  AboutCustomComponentConfig,
} from "../blocks";
import { withSelectFieldDefaults } from "../blocks/shared";
import type { PageBuilderConfig } from "../blocks/types";

const components = withSelectFieldDefaults({
  SiteLayoutFrame: SiteLayoutFrameComponentConfig,

  Section: SectionComponentConfig,
  Container: ContainerComponentConfig,
  TwoColumns: TwoColumnsComponentConfig,
  Spacer: SpacerComponentConfig,
  Divider: DividerComponentConfig,
  Grid: GridComponentConfig,
  Flex: FlexComponentConfig,

  Heading: HeadingComponentConfig,
  RichText: RichTextComponentConfig,
  Image: ImageComponentConfig,
  ImageText: ImageTextComponentConfig,
  Button: ButtonComponentConfig,
  ButtonGroup: ButtonGroupComponentConfig,
  Card: CardComponentConfig,
  Note: NoteComponentConfig,
  BadgeList: BadgeListComponentConfig,
  TagList: TagListComponentConfig,

  AboutSection: AboutSectionComponentConfig,
  FeatureGrid: FeatureGridComponentConfig,
  StatsSection: StatsSectionComponentConfig,
  CTASection: CTASectionComponentConfig,
  TimelineSection: TimelineSectionComponentConfig,
  FAQSection: FAQSectionComponentConfig,
  TestimonialSection: TestimonialSectionComponentConfig,
  CarouselSection: CarouselSectionComponentConfig,
  HeroBanner: HeroBannerComponentConfig,
  HeroSplit: HeroSplitComponentConfig,
  HeroCustom: HeroCustomComponentConfig,
  StatsCustom: StatsCustomComponentConfig,
  ProgramsCustom: ProgramsCustomComponentConfig,
  AboutCustom: AboutCustomComponentConfig,

  LatestPosts: LatestPostsComponentConfig,
  LatestAnnouncements: LatestAnnouncementsComponentConfig,
  StaffGrid: StaffGridComponentConfig,
  StaffProfileCard: StaffProfileCardComponentConfig,
  UnitList: UnitListComponentConfig,
  RelatedPosts: RelatedPostsComponentConfig,
  FitNavigationHeader: FitNavigationHeaderComponentConfig,
  FitFooter: FitFooterComponentConfig,
  NavigationMenu: NavigationMenuComponentConfig,
  Categories: CategoriesComponentConfig,
  PageLinks: PageLinksComponentConfig,
  LinkList: LinkListComponentConfig,
  ContactInfo: ContactInfoComponentConfig,
  SocialLinks: SocialLinksComponentConfig,
  NewsletterForm: NewsletterFormComponentConfig,
  CopyrightBar: CopyrightBarComponentConfig,
  AuthStatus: AuthStatusComponentConfig,
});

export const pageConfig: PageBuilderConfig = {
  categories: {
    layout_blocks: {
      title: "1. Bố cục",
      components: [
        "Section",
        "Container",
        "TwoColumns",
        "Spacer",
        "Divider",
        "Grid",
        "Flex",
      ],
    },
    content_blocks: {
      title: "2. Nội dung",
      components: [
        "Heading",
        "RichText",
        "Image",
        "ImageText",
        "Button",
        "ButtonGroup",
        "Card",
        "Note",
        "BadgeList",
        "TagList",
        "SocialLinks",
        "NewsletterForm",
        "CopyrightBar",
      ],
    },
    section_blocks: {
      title: "3. Khối giao diện",
      components: [
        "AboutSection",
        "FeatureGrid",
        "StatsSection",
        "CTASection",
        "TimelineSection",
        "FAQSection",
        "TestimonialSection",
        "CarouselSection",
        "HeroBanner",
        "HeroSplit",
        "HeroCustom",
        "StatsCustom",
        "ProgramsCustom",
        "AboutCustom",
      ],
    },
    dynamic_blocks: {
      title: "4. Khối dữ liệu",
      components: [
        "LatestPosts",
        "LatestAnnouncements",
        "StaffGrid",
        "StaffProfileCard",
        "UnitList",
        "RelatedPosts",
        "NavigationMenu",
        "Categories",
        "PageLinks",
        "LinkList",
        "ContactInfo",
      ],
    },
  },
  root: {
    render: ({ children }) => (
      <article className="font-sans space-y-12 rounded-3xl bg-bg p-4 sm:p-8">
        {children}
      </article>
    ),
  },
  components,
};
